on: [push]

jobs:
  hash:
    runs-on: ubuntu-latest
    name: hashes lua files
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: run hash action
        uses: ./.github/actions/action.yml